# Resistance mutations in aquatic plastisphere microbiomes

All script files are located in `sbatch_files/`. 

Steps:
1. Download the fastq data (specified in *download.txt*) using `download.sh` 
2. Run Pipeline 1, see TODO_URL_TO_IT for more details. TODO: Ok to link to it or jsut describe it?
3. Download the card database using `download_card.sh`
4. Build the database for MuMaMe using `mumame_build.sh`
5. Run MuMaMe using `split_mumame.sh`, it will be grouped according to *beginning_filenames.txt*, in order to speed up the operation.
6. The files *\*.table.txt* and *\*.per-mutation.txt* will be used below.

# Data analysis

In [ ]:
# Load Libraries
library("tidyverse")

# Load in data
table_DRR <- read_tsv("Mumame_results/mapping_results_DRR.table.txt", )
table_SRR142654147 <- read_tsv("Mumame_results/mapping_results_SRR2654147.table.txt")

# Load in the metadata tables
snps <- read_tsv("card-data/snps.txt")
aro_index <- read_tsv("card-data/aro_index.tsv")
aro_categories <- read_tsv("card-data/aro_categories.tsv")
aro_categories_index <- read_tsv("card-data/aro_categories_index.tsv")

Rows: 209 Columns: 37
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): Accession
dbl (36): DRR528401_1_val-Mut, DRR528401_2_val-Mut, DRR528402_1_val-Mut, DRR...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 96 Columns: 37
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): Accession
dbl (36): SRR26541470_1_val-Mut, SRR26541470_2_val-Mut, SRR26541471_1_val-Mu...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 3247 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (7): Name, Model Type, Parameter Type, Mutations, CARD Short Name, sourc...
dbl (1): Accession

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 6444 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (9): ARO Accession, Model Name, ARO Name, Protein Accession, DNA Accessi...
dbl (3): CVTERM ID, Model Sequence ID, Model ID

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 650 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (3): ARO Category, ARO Accession, ARO Name

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 6403 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (5): Protein Accession, DNA Accession, AMR Gene Family, Drug Class, Resi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [ ]:
# Test to combine the two dataframe, seems to work?
large_table <- full_join(table_DRR, table_SRR142654147)

# Show one row which contain data for both samples
large_table[which(large_table["Accession"] == "A67T+V90A:Staphylococcus aureus fusA with mutation conferring resistance to fusidic acid"), c(1:5, 39:63)

# Print the metadata tables
print("snps")
snps
print("aro_index")
aro_index
print("aro_categories")
aro_categories
print("aro_categories_index")
aro_categories_index

Rows: 209 Columns: 37
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): Accession
dbl (36): DRR528401_1_val-Mut, DRR528401_2_val-Mut, DRR528402_1_val-Mut, DRR...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 96 Columns: 37
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): Accession
dbl (36): SRR26541470_1_val-Mut, SRR26541470_2_val-Mut, SRR26541471_1_val-Mu...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Joining with `by = join_by(Accession)`
Rows: 3247 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (7): Name, Model Type, Parameter Type, Mutations, CARD Short Name, sourc...
dbl (1): Accession

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 6444 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (9): ARO Accession, Model Name, ARO Name, Protein Accession, DNA Accessi...
dbl (3): CVTERM ID, Model Sequence ID, Model ID

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 650 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (3): ARO Category, ARO Accession, ARO Name

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 6403 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (5): Protein Accession, DNA Accession, AMR Gene Family, Drug Class, Resi...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] "snps"

     Accession
1    3003817
2    3003817
3    3003818
4    3003818
5    3003818
6    3004145
7    3003788
8    3007073
9    3007073
10   3007073
11   3007073
12   3007073
13   3007527
14   3007527
15   3007527
16   3007527
17   3007527
18   3007527
19   3007527
20   3007527
21   3007527
22   3007527
23   3007527
24   3000828
25   3000829
26   3003297
27   3003297
28   3003302
29   3003302
30   3003302
⋮    ⋮
3218 3003043
3219 3003387
3220 3007531
3221 3007531
3222 3007531
3223 3004171
3224 3003359
3225 3003479
3226 3003479
3227 3003479
3228 3005083
3229 3005083
3230 3005083
3231 3005083
3232 3005083
3233 3005083
3234 3005081
3235 3005081
3236 3007759
3237 3007759
3238 3004059
3239 3004060
3240 3003305
3241 3003305
3242 3003309
3243 3003309
3244 3003309
3245 3003309
3246 3007794
3247 3007843
     Name
1    Acinetobacter baumannii gyrA conferring resistance to fluoroquinolones
2    Acinetobacter baumannii gyrA conferring resistance to fluoroquinolones
3    Acinetobacter baumannii parC conferring resistance to fluoroquinolones
4    Acinetobacter baumannii parC conferring resistance to fluoroquinolones
5    Acinetobacter baumannii parC conferring resistance to fluoroquinolones
6    AxyZ
7    Bacillus subtilis pgsA with mutation conferring resistance to daptomycin
8    Bacillus subtilis rpoB mutants conferring resistance to rifampin
9    Bacillus subtilis rpoB mutants conferring resistance to rifampin
10   Bacillus subtilis rpoB mutants conferring resistance to rifampin
11   Bacillus subtilis rpoB mutants conferring resistance to rifampin
12   Bacillus subtilis rpoB mutants conferring resistance to rifampin
13   Bacillus subtilis rpsE mutations conferring resistance to spectinomycin
14   Bacillus subtilis rpsE mutations conferring resistance to spectinomycin
15   Bacillus subtilis rpsE mutations conferring resistance to spectinomycin
16   Bacillus subtilis rpsE mutations conferring resistance to spectinomycin
17   Bacillus subtilis rpsE mutations conferring resistance to spectinomycin
18   Bacillus subtilis rpsE mutations conferring resistance to spectinomycin
19   Bacillus subtilis rpsE mutations conferring resistance to spectinomycin
20   Bacillus subtilis rpsE mutations conferring resistance to spectinomycin
21   Bacillus subtilis rpsE mutations conferring resistance to spectinomycin
22   Bacillus subtilis rpsE mutations conferring resistance to spectinomycin
23   Bacillus subtilis rpsE mutations conferring resistance to spectinomycin
24   baeR
25   baeS
26   Bartonella bacilliformis gyrA conferring resistance to fluoroquinolones
27   Bartonella bacilliformis gyrA conferring resistance to fluoroquinolones
28   Bartonella bacilliformis gyrB conferring resistance to aminocoumarin
29   Bartonella bacilliformis gyrB conferring resistance to aminocoumarin
30   Bartonella bacilliformis gyrB conferring resistance to aminocoumarin
⋮    ⋮
3218 Streptococcus pneumoniae PBP2x conferring resistance to amoxicillin
3219 Streptococcus pyogenes folP with mutation conferring resistance to sulfonamides
3220 Streptococcus pyogenes PBP2x conferring resistance to beta-lactam antibiotics
3221 Streptococcus pyogenes PBP2x conferring resistance to beta-lactam antibiotics
3222 Streptococcus pyogenes PBP2x conferring resistance to beta-lactam antibiotics
3223 Streptomyces ambofaciens 23S rRNA with mutation conferring resistance to macrolide antibiotics
3224 Streptomyces cinnamoneus EF-Tu mutants conferring resistance to elfamycin
3225 tetR
3226 tetR
3227 tetR
3228 Thermus thermophilus 23s rRNA conferring resistance to pleuromutilin antibiotics
3229 Thermus thermophilus 23s rRNA conferring resistance to pleuromutilin antibiotics
3230 Thermus thermophilus 23s rRNA conferring resistance to pleuromutilin antibiotics
3231 Thermus thermophilus 23s rRNA conferring resistance to pleuromutilin antibiotics
3232 Thermus thermophilus 23s rRNA conferring resistance to pleuromutilin antibiotics
3233 Thermus thermophilus 23s rRNA conferring resistance to pleuromutilin antibiotics
3234 Thermus thermophilus uL3 mutations conferring resistance to pleuromutilin antibiotics
3235 Thermus thermophilus uL3 mutations conferring resistance to pleuromutilin antibiotics
3236 Treponema pallidum 23S rRNA with mutation conferring resistance to erythromycin
3237 Treponema pallidum 23S rRNA with mutation conferring resistance to erythromycin
3238 Type A NfxB
3239 Type B NfxB
3240 Ureaplasma urealyticum gyrB conferring resistance to fluoroquinolones
3241 Ureaplasma urealyticum gyrB conferring resistance to fluoroquinolones
3242 Ureaplasma urealyticum parC conferring resistance to fluoroquinolones
3243 Ureaplasma urealyticum parC conferring resistance to fluoroquinolones
3244 Ureaplasma urealyticum parC conferring resistance to fluoroquinolones
3245 Ureaplasma urealyticum parC conferring resistance to fluoroquinolones
3246 Vibrio vulnificus rpoB mutants conferring resistance to rifampin
3247 VRA-F
     Model Type                   Parameter Type               Mutations
1    protein variant model        single resistance variant    G79C
2    protein variant model        single resistance variant    S81L
3    protein variant model        single resistance variant    V104I
4    protein variant model        single resistance variant    S84L
5    protein variant model        single resistance variant    D105E
6    protein variant model        single resistance variant    V29G
7    protein variant model        single resistance variant    A64V
8    protein variant model        single resistance variant    Q469K
9    protein variant model        single resistance variant    A478N
10   protein variant model        single resistance variant    H482Y
11   protein variant model        single resistance variant    S487L
12   protein variant model        single resistance variant    Q469R
13   protein variant model        single resistance variant    C88G
14   protein variant model        single resistance variant    G83A
15   protein variant model        single resistance variant    G83C
16   protein variant model        single resistance variant    G64C
17   protein variant model        multiple resistance variants G82T,G86T
18   protein variant model        single resistance variant    G89C
19   protein variant model        single resistance variant    A77T
20   protein variant model        single resistance variant    C85G
21   protein variant model        single resistance variant    A67G
22   protein variant model        single resistance variant    G73T
23   protein variant model        single resistance variant    G83T
24   protein overexpression model single resistance variant    S104N
25   protein overexpression model single resistance variant    D89V
26   protein variant model        single resistance variant    D90G
27   protein variant model        single resistance variant    D95N
28   protein variant model        single resistance variant    T214I
29   protein variant model        single resistance variant    G124S
30   protein variant model        single resistance variant    T214A
⋮    ⋮                            ⋮                            ⋮
3218 protein variant model        single resistance variant    L546V
3219 protein variant model        single resistance variant    F25I
3220 protein variant model        single resistance variant    P601L
3221 protein variant model        single resistance variant    M593T
3222 protein variant model        single resistance variant    T553K
3223 rRNA gene variant model      single resistance variant    a2305g
3224 protein variant model        single resistance variant    A379T
3225 protein overexpression model single resistance variant    N82H
3226 protein overexpression model single resistance variant    H64Y
3227 protein overexpression model single resistance variant    T103I
3228 rRNA gene variant model      single resistance variant    t2504g
3229 rRNA gene variant model      single resistance variant    g2061a
3230 rRNA gene variant model      single resistance variant    g2061t
3231 rRNA gene variant model      single resistance variant    a2451t
3232 rRNA gene variant model      single resistance variant    c2452t
3233 rRNA gene variant model      single resistance variant    t2500a
3234 protein variant model        single resistance variant    R144C
3235 protein variant model        single resistance variant    R144H
3236 rRNA gene variant model      single resistance variant    a2101g
3237 rRNA gene variant model      single resistance variant    a2100g
3238 protein overexpression model single resistance variant    R42G
3239 protein overexpression model single resistance variant    H87R
3240 protein variant model        single resistance variant    E502Q
3241 protein variant model        single resistance variant    P462S
3242 protein variant model        single resistance variant    S83L
3243 protein variant model        single resistance variant    E87Q
3244 protein variant model        single resistance variant    S84P
3245 protein variant model        single resistance variant    S83W
3246 protein variant model        single resistance variant    S522L
3247 protein variant model        single resistance variant    K84E
     CARD Short Name source    citation
1    Abau_gyrA_FLO   Curated-R 15282231
2    Abau_gyrA_FLO   Curated-R 15282231
3    Abau_parC_FLO   Curated-R 36010006
4    Abau_parC_FLO   Curated-R 36010006
5    Abau_parC_FLO   Curated-R 36010006
6    AxyZ            Curated-R 28584156
7    Bsub_pgsA_DAP   Curated-R 21709092
8    Bsub_rpoB_RIF   Curated-R 11101662
9    Bsub_rpoB_RIF   Curated-R 12169622
10   Bsub_rpoB_RIF   Curated-R 11101662
11   Bsub_rpoB_RIF   Curated-R 12169622
12   Bsub_rpoB_RIF   Curated-R 11101662
13   Bsub_rpsE_SPT   Curated-R 34339280
14   Bsub_rpsE_SPT   Curated-R 34339280
15   Bsub_rpsE_SPT   Curated-R 34339280
16   Bsub_rpsE_SPT   Curated-R 34339280
17   Bsub_rpsE_SPT   Curated-R 34339280
18   Bsub_rpsE_SPT   Curated-R 34339280
19   Bsub_rpsE_SPT   Curated-R 34339280
20   Bsub_rpsE_SPT   Curated-R 34339280
21   Bsub_rpsE_SPT   Curated-R 34339280
22   Bsub_rpsE_SPT   Curated-R 34339280
23   Bsub_rpsE_SPT   Curated-R 34339280
24   baeR            Curated-R 37345941
25   baeS            Curated-R 37345941
26   Bbac_gyrA_FLO   Curated-R 12499219
27   Bbac_gyrA_FLO   Curated-R 12499219
28   Bbac_gyrA_AMU   Curated-R 9797224
29   Bbac_gyrA_AMU   Curated-R 9797224
30   Bbac_gyrA_AMU   Curated-R 9797224
⋮    ⋮               ⋮         ⋮
3218 Spne_PBP2x_AMX  Curated-R 18394970
3219 Spyo_folP_SLF   Curated-R 9593127
3220 Spyo_PBP2x_BLA  Curated-R 36374114
3221 Spyo_PBP2x_BLA  Curated-R 36374114
3222 Spyo_PBP2x_BLA  Curated-R 31630171
3223 Samb_23S_MAC    Curated-R 2834204
3224 Scin_EFTu_ELF   Curated-R 9043138
3225 tetR            Curated-R 3062183
3226 tetR            Curated-R 3062183
3227 tetR            Curated-R 3062183
3228 Tthe_23S_PLM    Curated-R 32526926
3229 Tthe_23S_PLM    Curated-R 32526926
3230 Tthe_23S_PLM    Curated-R 32526926
3231 Tthe_23S_PLM    Curated-R 32526926
3232 Tthe_23S_PLM    Curated-R 32526926
3233 Tthe_23S_PLM    Curated-R 32526926
3234 Tthe_uL3_PLM    Curated-R 32526926
3235 Tthe_uL3_PLM    Curated-R 32526926
3236 Tpal_23S_ERY    Curated-R 19429763
3237 Tpal_23S_ERY    Curated-R 15247355
3238 Type_A_NfxB     Curated-R 1330820
3239 Type_B_NfxB     Curated-R 8878035
3240 Uure_gyrB_FLO   Curated-R 27884651
3241 Uure_gyrB_FLO   Curated-R 25645833
3242 Uure_parC_FLO   Curated-R 25645833
3243 Uure_parC_FLO   Curated-R 27884651
3244 Uure_parC_FLO   Curated-R 25645833
3245 Uure_parC_FLO   Curated-R 25645833
3246 Vvul_rpoB_RIF   Curated-R 37877661
3247 VRA-F           Curated-R 38838390

[1] "aro_index"

     ARO Accession CVTERM ID Model Sequence ID Model ID
1    ARO:3005099   43314     6143              3831
2    ARO:3002523   38923     8144              1781
3    ARO:3002524   38924       85               746
4    ARO:3002525   38925     4719              1246
5    ARO:3002526   38926      228              1415
6    ARO:3002527   38927     5510              2832
7    ARO:3004628   42613     5361              3327
8    ARO:3003988   40870     3860              2524
9    ARO:3002528   38928     8360                39
10   ARO:3002530   38930      224               575
11   ARO:3002600   39000      271               209
12   ARO:3002531   38931       47              1131
13   ARO:3002529   38929      223               742
14   ARO:3002533   38933     4266               478
15   ARO:3002534   38934       10               925
16   ARO:3002535   38935      616              1378
17   ARO:3004623   42605     5344              3322
18   ARO:3004621   42600     5340              3321
19   ARO:3005085   43296     6120              3820
20   ARO:3002536   38936        6              1879
21   ARO:3002537   38937     5232               410
22   ARO:3002538   38938        9                51
23   ARO:3002539   38939     3715               639
24   ARO:3005061   43265     6130              3801
25   ARO:3002543   38943      655              2030
26   ARO:3002540   38940      659              1105
27   ARO:3002541   38941      694               653
28   ARO:3002542   38942       12               501
29   ARO:3002544   38944     4702              1483
30   ARO:3002583   38983     5868               300
⋮    ⋮             ⋮         ⋮                 ⋮
6415 ARO:3007815   46602      8859             6039
6416 ARO:3007816   46603      8860             6040
6417 ARO:3002278   38678      1084              262
6418 ARO:3007817   46604      8861             6041
6419 ARO:3007818   46605      8862             6042
6420 ARO:3007819   46606      8863             6043
6421 ARO:3007820   46607      8864             6044
6422 ARO:3007821   46608      8865             6045
6423 ARO:3007822   46609      8866             6046
6424 ARO:3007823   46610      8867             6047
6425 ARO:3007824   46611      8868             6048
6426 ARO:3009092   47884     11337             8510
6427 ARO:3009093   47885     11338             8511
6428 ARO:3002279   38679      1166             1857
6429 ARO:3009094   47886     11339             8512
6430 ARO:3009095   47887     11340             8513
6431 ARO:3005015   43204      6048             3758
6432 ARO:3004476   41736      5366             2907
6433 ARO:3003061   39495        62             1223
6434 ARO:3007843   46632      8888             6065
6435 ARO:3007435   46193      8652             5933
6436 ARO:3003558   40163      3318              980
6437 ARO:3005040   43238      6076             3783
6438 ARO:3007005   45467      8098             5723
6439 ARO:3003063   39497       489             1826
6440 ARO:3003064   39498       536              350
6441 ARO:3009096   47888     11341             8514
6442 ARO:3003952   40722      5261             2424
6443 ARO:3005035   43233      6072             3779
6444 ARO:3007006   45468      8099             5724
     Model Name
1    23S rRNA (adenine(2058)-N(6))-methyltransferase Erm(A)
2    AAC(2')-Ia
3    AAC(2')-Ib
4    AAC(2')-Ic
5    AAC(2')-Id
6    AAC(2')-Ie
7    AAC(2')-IIa
8    AAC(2')-IIb
9    AAC(3)-Ia
10   AAC(3)-Ib
11   AAC(3)-Ib/AAC(6')-Ib''
12   AAC(3)-Ic
13   AAC(3)-Id
14   AAC(3)-IIa
15   AAC(3)-IIb
16   AAC(3)-IIc
17   AAC(3)-IId
18   AAC(3)-IIe
19   AAC(3)-IIg
20   AAC(3)-IIIa
21   AAC(3)-IIIb
22   AAC(3)-IIIc
23   AAC(3)-IVa
24   AAC(3)-IVb
25   AAC(3)-IXa
26   AAC(3)-VIa
27   AAC(3)-VIIa
28   AAC(3)-VIIIa
29   AAC(3)-Xa
30   AAC(6')-29a
⋮    ⋮
6415 VIM-78
6416 VIM-79
6417 VIM-8
6418 VIM-80
6419 VIM-81
6420 VIM-82
6421 VIM-83
6422 VIM-84
6423 VIM-85
6424 VIM-86
6425 VIM-87
6426 VIM-88
6427 VIM-89
6428 VIM-9
6429 VIM-90
6430 VIM-91
6431 VMB-1
6432 vmlR
6433 vph
6434 VRA-F
6435 WUS-1
6436 y56 beta-lactamase
6437 YajC
6438 YEM-1
6439 ykkC
6440 ykkD
6441 YOC-1
6442 YojI
6443 YRC-1
6444 ZOG-1
     ARO Name                                               Protein Accession
1    23S rRNA (adenine(2058)-N(6))-methyltransferase Erm(A) AAB60941.1
2    AAC(2')-Ia                                             AAA03550.1
3    AAC(2')-Ib                                             AAC44793.1
4    AAC(2')-Ic                                             CCP42991.1
5    AAC(2')-Id                                             AAB41701.1
6    AAC(2')-Ie                                             CAC32082.1
7    AAC(2')-IIa                                            BAM16262.1
8    AAC(2')-IIb                                            APB03221.1
9    AAC(3)-Ia                                              AAG15269.1
10   AAC(3)-Ib                                              AAA88422.1
11   AAC(3)-Ib/AAC(6')-Ib3 bifunctional protein             AAL82588.1
12   AAC(3)-Ic                                              CAD53575.1
13   AAC(3)-Id                                              AAR21614.1
14   AAC(3)-IIa                                             CAA31895.1
15   AAC(3)-IIb                                             AAA26548.1
16   AAC(3)-IIc                                             CAA38525.1
17   AAC(3)-IId                                             ABS70977.1
18   AAC(3)-IIe                                             ABS70978.1
19   AAC(3)-IIg                                             QKT21444.1
20   AAC(3)-IIIa                                            CAA39184.1
21   AAC(3)-IIIb                                            KSC15183.1
22   AAC(3)-IIIc                                            AAA25683.1
23   AAC(3)-IVa                                             ABB43029.1
24   AAC(3)-IVb                                             QEQ43476.1
25   AAC(3)-IXa                                             AAA25334.1
26   AAC(3)-VIa                                             AAA16194.1
27   AAC(3)-VIIa                                            AAA88552.1
28   AAC(3)-VIIIa                                           AAA26685.1
29   AAC(3)-Xa                                              BAA78619.1
30   AAC(6')-29a                                            WP_064190968.1
⋮    ⋮                                                      ⋮
6415 VIM-78                                                 UBK22127.1
6416 VIM-79                                                 UBL87558.1
6417 VIM-8                                                  AAS13759.1
6418 VIM-80                                                 MBC9045152.1
6419 VIM-81                                                 UNZ81762.1
6420 VIM-82                                                 WP_238839790.1
6421 VIM-83                                                 UWI53403.1
6422 VIM-84                                                 UWQ12890.1
6423 VIM-85                                                 UWQ12891.1
6424 VIM-86                                                 WAU52774.1
6425 VIM-87                                                 EME7055635.1
6426 VIM-88                                                 XHO32912.1
6427 VIM-89                                                 XHO32913.1
6428 VIM-9                                                  AAS13760.1
6429 VIM-90                                                 XHO32914.1
6430 VIM-91                                                 MFC1252596.1
6431 VMB-1                                                  QGQ32905.1
6432 vmlR                                                   NP_388442.1
6433 vph                                                    CAA26235.1
6434 VRA-F                                                  WP_323056190.1
6435 WUS-1                                                  UPP01678.1
6436 y56 beta-lactamase                                     AAX55643.1
6437 YajC                                                   TKW44661.1
6438 YEM-1                                                  WP_004874166.1
6439 ykkC                                                   CAB13166.1
6440 ykkD                                                   CAB13167.1
6441 YOC-1                                                  QIU91361.1
6442 YojI                                                   AAC75271.1
6443 YRC-1                                                  ABA70720.1
6444 ZOG-1                                                  WP_013992183.1
     DNA Accession
1    AF002716.1
2    L06156.2
3    U41471.1
4    AL123456.3
5    U72743.1
6    AL583926.1
7    AB669090.1
8    KX531051.1
9    U12338.3
10   L06157.1
11   AF355189.1
12   AJ511268.1
13   AY458224.1
14   X13543.1
15   M97172.1
16   X54723.1
17   EU022314.1
18   EU022315.1
19   MT090547.1
20   X55652.1
21   LLLC01000048.1
22   L06161.1
23   DQ241380.1
24   MN366378.1
25   M55427.1
26   M88012.1
27   M22999.1
28   M55426.1
29   AB028210.1
30   NG_048575.1
⋮    ⋮
6415 OK180983.1
6416 OK217280.1
6417 AY524987.1
6418 JACTAE010000183.1
6419 ON059758.1
6420 NG_088450.1
6421 OP353772.1
6422 ON688661.1
6423 ON688662.1
6424 OP998371.1
6425 ABPYXB010000003.1
6426 PQ394569.1
6427 PQ394570.1
6428 AY524988.1
6429 PQ394571.1
6430 JBHOJN010000016.1
6431 MN719868.1
6432 NC_000964.3
6433 X02393.1
6434 NZ_JAYEPV010000001.1
6435 OL872181.1
6436 AY954728.1
6437 VAOQ01003483.1
6438 NG_070759.1
6439 AL009126.1
6440 AL009126.1
6441 CP050811.1
6442 U00096.3
6443 DQ185144.1
6444 NG_057434.1
     AMR Gene Family
1    Erm 23S ribosomal RNA methyltransferase
2    AAC(2')
3    AAC(2')
4    AAC(2')
5    AAC(2')
6    AAC(2')
7    AAC(2')
8    AAC(2')
9    AAC(3)
10   AAC(3)
11   aminoglycoside bifunctional resistance protein
12   AAC(3)
13   AAC(3)
14   AAC(3)
15   AAC(3)
16   AAC(3)
17   AAC(3)
18   AAC(3)
19   AAC(3)
20   AAC(3)
21   AAC(3)
22   AAC(3)
23   AAC(3)
24   AAC(3)
25   AAC(3)
26   AAC(3)
27   AAC(3)
28   AAC(3)
29   AAC(3)
30   AAC(6')
⋮    ⋮
6415 VIM beta-lactamase
6416 VIM beta-lactamase
6417 VIM beta-lactamase
6418 VIM beta-lactamase
6419 VIM beta-lactamase
6420 VIM beta-lactamase
6421 VIM beta-lactamase
6422 VIM beta-lactamase
6423 VIM beta-lactamase
6424 VIM beta-lactamase
6425 VIM beta-lactamase
6426 VIM beta-lactamase
6427 VIM beta-lactamase
6428 VIM beta-lactamase
6429 VIM beta-lactamase
6430 VIM beta-lactamase
6431 VMB beta-lactamase
6432 Miscellaneous ABC-F subfamily ATP-binding cassette ribosomal protection proteins
6433 viomycin phosphotransferase
6434 ATP-binding cassette (ABC) antibiotic efflux pump
6435 WUS beta-lactamase
6436 BlaA beta-lactamase
6437 resistance-nodulation-cell division (RND) antibiotic efflux pump
6438 YEM beta-lactamase
6439 small multidrug resistance (SMR) antibiotic efflux pump
6440 small multidrug resistance (SMR) antibiotic efflux pump
6441 YOC beta-lactamase
6442 ATP-binding cassette (ABC) antibiotic efflux pump
6443 YRC beta-lactamase
6444 ZOG beta-lactamase
     Drug Class
1    lincosamide antibiotic;macrolide antibiotic;streptogramin antibiotic
2    aminoglycoside antibiotic
3    aminoglycoside antibiotic
4    aminoglycoside antibiotic
5    aminoglycoside antibiotic
6    aminoglycoside antibiotic
7    aminoglycoside antibiotic
8    aminoglycoside antibiotic
9    aminoglycoside antibiotic
10   aminoglycoside antibiotic
11   aminoglycoside antibiotic
12   aminoglycoside antibiotic
13   aminoglycoside antibiotic
14   aminoglycoside antibiotic
15   aminoglycoside antibiotic
16   aminoglycoside antibiotic
17   aminoglycoside antibiotic
18   aminoglycoside antibiotic
19   aminoglycoside antibiotic
20   aminoglycoside antibiotic
21   aminoglycoside antibiotic
22   aminoglycoside antibiotic
23   aminoglycoside antibiotic
24   aminoglycoside antibiotic
25   aminoglycoside antibiotic
26   aminoglycoside antibiotic
27   aminoglycoside antibiotic
28   aminoglycoside antibiotic
29   aminoglycoside antibiotic
30   aminoglycoside antibiotic
⋮    ⋮
6415 carbapenem;cephalosporin;penicillin beta-lactam
6416 carbapenem;cephalosporin;penicillin beta-lactam
6417 carbapenem;cephalosporin;penicillin beta-lactam
6418 carbapenem;cephalosporin;penicillin beta-lactam
6419 carbapenem;cephalosporin;penicillin beta-lactam
6420 carbapenem;cephalosporin;penicillin beta-lactam
6421 carbapenem;cephalosporin;penicillin beta-lactam
6422 carbapenem;cephalosporin;penicillin beta-lactam
6423 carbapenem;cephalosporin;penicillin beta-lactam
6424 carbapenem;cephalosporin;penicillin beta-lactam
6425 carbapenem;cephalosporin;penicillin beta-lactam
6426 carbapenem;cephalosporin;penicillin beta-lactam
6427 carbapenem;cephalosporin;penicillin beta-lactam
6428 carbapenem;cephalosporin;penicillin beta-lactam
6429 carbapenem;cephalosporin;penicillin beta-lactam
6430 carbapenem;cephalosporin;penicillin beta-lactam
6431 carbapenem;cephalosporin;penicillin beta-lactam
6432 lincosamide antibiotic;nucleoside antibiotic;pleuromutilin antibiotic;streptogramin A antibiotic;streptogramin B antibiotic;streptogramin antibiotic
6433 peptide antibiotic
6434 glycopeptide antibiotic
6435 carbapenem;penicillin beta-lactam
6436 cephalosporin;penicillin beta-lactam
6437 cephalosporin;disinfecting agents and antiseptics;fluoroquinolone antibiotic;glycopeptide antibiotic;glycylcycline;oxazolidinone antibiotic;penicillin beta-lactam;phenicol antibiotic;rifamycin antibiotic;tetracycline antibiotic
6438 carbapenem
6439 aminoglycoside antibiotic;phenicol antibiotic;tetracycline antibiotic
6440 aminoglycoside antibiotic;phenicol antibiotic;tetracycline antibiotic
6441 cephalosporin
6442 peptide antibiotic
6443 cephalosporin;penicillin beta-lactam
6444 carbapenem
     Resistance Mechanism         CARD Short Name
1    antibiotic target alteration Spyo_ErmA_MLSb
2    antibiotic inactivation      AAC(2')-Ia
3    antibiotic inactivation      AAC(2')-Ib
4    antibiotic inactivation      AAC(2')-Ic
5    antibiotic inactivation      AAC(2')-Id
6    antibiotic inactivation      AAC(2')-Ie
7    antibiotic inactivation      AAC(2')-IIa
8    antibiotic inactivation      AAC(2')-IIb
9    antibiotic inactivation      AAC(3)-Ia
10   antibiotic inactivation      AAC(3)-Ib
11   antibiotic inactivation      AAC_3Ib_AAC_6Ib
12   antibiotic inactivation      AAC(3)-Ic
13   antibiotic inactivation      AAC(3)-Id
14   antibiotic inactivation      AAC(3)-IIa
15   antibiotic inactivation      AAC(3)-IIb
16   antibiotic inactivation      AAC(3)-IIc
17   antibiotic inactivation      AAC(3)-IId
18   antibiotic inactivation      AAC(3)-IIe
19   antibiotic inactivation      AAC(3)-IIg
20   antibiotic inactivation      AAC(3)-IIIa
21   antibiotic inactivation      AAC(3)-IIIb
22   antibiotic inactivation      AAC(3)-IIIc
23   antibiotic inactivation      AAC(3)-IVa
24   antibiotic inactivation      AAC(3)-IVb
25   antibiotic inactivation      AAC(3)-IXa
26   antibiotic inactivation      AAC(3)-VIa
27   antibiotic inactivation      AAC(3)-VIIa
28   antibiotic inactivation      AAC(3)-VIIIa
29   antibiotic inactivation      AAC(3)-Xa
30   antibiotic inactivation      AAC(6')-29a
⋮    ⋮                            ⋮
6415 antibiotic inactivation      VIM-78
6416 antibiotic inactivation      VIM-79
6417 antibiotic inactivation      VIM-8
6418 antibiotic inactivation      VIM-80
6419 antibiotic inactivation      VIM-81
6420 antibiotic inactivation      VIM-82
6421 antibiotic inactivation      VIM-83
6422 antibiotic inactivation      VIM-84
6423 antibiotic inactivation      VIM-85
6424 antibiotic inactivation      VIM-86
6425 antibiotic inactivation      VIM-87
6426 antibiotic inactivation      VIM-88
6427 antibiotic inactivation      VIM-89
6428 antibiotic inactivation      VIM-9
6429 antibiotic inactivation      VIM-90
6430 antibiotic inactivation      VIM-91
6431 antibiotic inactivation      VMB-1
6432 antibiotic target protection vmlR
6433 antibiotic inactivation      vph
6434 antibiotic efflux            VRA-F
6435 antibiotic inactivation      WUS-1
6436 antibiotic inactivation      Yent_y56
6437 antibiotic efflux            YajC
6438 antibiotic inactivation      YEM-1
6439 antibiotic efflux            ykkC
6440 antibiotic efflux            ykkD
6441 antibiotic inactivation      YOC-1
6442 antibiotic efflux            YojI
6443 antibiotic inactivation      YRC-1
6444 antibiotic inactivation      ZOG-1

[1] "aro_categories"

    ARO Category         ARO Accession
1   AMR Gene Family      ARO:3004272
2   AMR Gene Family      ARO:3004271
3   AMR Gene Family      ARO:3003666
4   AMR Gene Family      ARO:3003976
5   AMR Gene Family      ARO:3003667
6   AMR Gene Family      ARO:3003668
7   AMR Gene Family      ARO:3003669
8   AMR Gene Family      ARO:3004936
9   AMR Gene Family      ARO:3004187
10  AMR Gene Family      ARO:3004057
11  AMR Gene Family      ARO:3004125
12  AMR Gene Family      ARO:3004172
13  AMR Gene Family      ARO:3004188
14  AMR Gene Family      ARO:3004178
15  AMR Gene Family      ARO:3004182
16  AMR Gene Family      ARO:3005001
17  AMR Gene Family      ARO:3004259
18  AMR Gene Family      ARO:3000341
19  AMR Gene Family      ARO:3000322
20  AMR Gene Family      ARO:3000345
21  AMR Gene Family      ARO:3005113
22  AMR Gene Family      ARO:3005387
23  AMR Gene Family      ARO:3000073
24  AMR Gene Family      ARO:3004358
25  AMR Gene Family      ARO:3003581
26  AMR Gene Family      ARO:3000072
27  AMR Gene Family      ARO:3005460
28  AMR Gene Family      ARO:3004545
29  AMR Gene Family      ARO:3003846
30  AMR Gene Family      ARO:3000089
⋮   ⋮                    ⋮
621 Drug Class           ARO:3007162
622 Drug Class           ARO:3007155
623 Drug Class           ARO:3007560
624 Drug Class           ARO:3005167
625 Drug Class           ARO:3000157
626 Drug Class           ARO:3007159
627 Drug Class           ARO:0000034
628 Drug Class           ARO:0000026
629 Drug Class           ARO:0000050
630 Drug Class           ARO:3000282
631 Drug Class           ARO:3003401
632 Drug Class           ARO:3005172
633 Drug Class           ARO:3007034
634 Drug Class           ARO:3000050
635 Drug Class           ARO:3007177
636 Drug Class           ARO:3007156
637 Drug Class           ARO:3007161
638 Drug Class           ARO:3007164
639 Drug Class           ARO:3007499
640 Drug Class           ARO:3007160
641 Resistance Mechanism ARO:0010000
642 Resistance Mechanism ARO:0001004
643 Resistance Mechanism ARO:0001001
644 Resistance Mechanism ARO:3007609
645 Resistance Mechanism ARO:0001003
646 Resistance Mechanism ARO:0001002
647 Resistance Mechanism ARO:3007115
648 Resistance Mechanism ARO:3000244
649 Resistance Mechanism ARO:3003764
650 Resistance Mechanism ARO:3007424
    ARO Name
1   16S rRNA methyltransferase (A1408)
2   16S rRNA methyltransferase (G1405)
3   16s rRNA with mutation conferring resistance to aminoglycoside antibiotics
4   16S rRNA with mutation conferring resistance to pactamycin
5   16s rRNA with mutation conferring resistance to peptide antibiotics
6   16s rRNA with mutation conferring resistance to polyamine antibiotics
7   16S rRNA with mutation conferring resistance to tetracycline derivatives
8   23s rRNA with mutation conferring resistance to aminoglycoside antibiotics
9   23S rRNA with mutation conferring resistance to lincosamide antibiotics
10  23S rRNA with mutation conferring resistance to linezolid antibiotics
11  23S rRNA with mutation conferring resistance to macrolide antibiotics
12  23S rRNA with mutation conferring resistance to oxazolidinone antibiotics
13  23S rRNA with mutation conferring resistance to phenicol antibiotics
14  23S rRNA with mutation conferring resistance to pleuromutilin antibiotics
15  23S rRNA with mutation conferring resistance to streptogramins antibiotics
16  50S rRNA with mutation conferring resistance to macrolide antibiotics
17  AAC(1)
18  AAC(2')
19  AAC(3)
20  AAC(6')
21  AAC(6')-Ib-cr
22  AAK beta-lactamase
23  ACC beta-lactamase
24  ACI beta-lactamase
25  Acinetobacter mutant Lpx gene conferring resistance to colistin
26  ACT beta-lactamase
27  ADC beta-lactamases pending classification for carbapenemase activity
28  ADC beta-lactamase with carbapenemase activity
29  ADC beta-lactamase without carbapenemase activity
30  AER beta-lactamase
⋮   ⋮
621 protegrin-1-like antibiotic
622 pyrazine antibiotic
623 pyrimidine antifungal drug
624 quinone with antibiotic activity
625 rifamycin antibiotic
626 salicylic acid antibiotic
627 streptogramin A antibiotic
628 streptogramin antibiotic
629 streptogramin B antibiotic
630 sulfonamide antibiotic
631 sulfone antibiotic
632 terpene with antibiotic activity
633 tetracenomycin antibiotic
634 tetracycline antibiotic
635 thiazolide antibiotic
636 thioamide antibiotic
637 thiosemicarbazone antibiotic
638 triazaacenaphthylene antibiotic
639 triazole antibiotic
640 zoliflodacin-like antibiotic
641 antibiotic efflux
642 antibiotic inactivation
643 antibiotic target alteration
644 antibiotic target overexpression
645 antibiotic target protection
646 antibiotic target replacement
647 modification to cell morphology
648 reduced permeability to antibiotic
649 resistance by absence
650 resistance by host-dependent nutrient acquisition

[1] "aro_categories_index"

     Protein Accession DNA Accession
1    AAB60941.1        AF002716.1
2    AAA03550.1        L06156.2
3    AAC44793.1        U41471.1
4    CCP42991.1        AL123456.3
5    AAB41701.1        U72743.1
6    CAC32082.1        AL583926.1
7    BAM16262.1        AB669090.1
8    APB03221.1        KX531051.1
9    AAG15269.1        U12338.3
10   AAA88422.1        L06157.1
11   AAL82588.1        AF355189.1
12   CAD53575.1        AJ511268.1
13   AAR21614.1        AY458224.1
14   CAA31895.1        X13543.1
15   AAA26548.1        M97172.1
16   CAA38525.1        X54723.1
17   ABS70977.1        EU022314.1
18   ABS70978.1        EU022315.1
19   QKT21444.1        MT090547.1
20   CAA39184.1        X55652.1
21   KSC15183.1        LLLC01000048.1
22   AAA25683.1        L06161.1
23   ABB43029.1        DQ241380.1
24   QEQ43476.1        MN366378.1
25   AAA25334.1        M55427.1
26   AAA16194.1        M88012.1
27   AAA88552.1        M22999.1
28   AAA26685.1        M55426.1
29   BAA78619.1        AB028210.1
30   WP_064190968.1    NG_048575.1
⋮    ⋮                 ⋮
6374 UBK22127.1        OK180983.1
6375 UBL87558.1        OK217280.1
6376 AAS13759.1        AY524987.1
6377 MBC9045152.1      JACTAE010000183.1
6378 UNZ81762.1        ON059758.1
6379 WP_238839790.1    NG_088450.1
6380 UWI53403.1        OP353772.1
6381 UWQ12890.1        ON688661.1
6382 UWQ12891.1        ON688662.1
6383 WAU52774.1        OP998371.1
6384 EME7055635.1      ABPYXB010000003.1
6385 XHO32912.1        PQ394569.1
6386 XHO32913.1        PQ394570.1
6387 AAS13760.1        AY524988.1
6388 XHO32914.1        PQ394571.1
6389 MFC1252596.1      JBHOJN010000016.1
6390 QGQ32905.1        MN719868.1
6391 NP_388442.1       NC_000964.3
6392 CAA26235.1        X02393.1
6393 WP_323056190.1    NZ_JAYEPV010000001.1
6394 UPP01678.1        OL872181.1
6395 AAX55643.1        AY954728.1
6396 TKW44661.1        VAOQ01003483.1
6397 WP_004874166.1    NG_070759.1
6398 CAB13166.1        AL009126.1
6399 CAB13167.1        AL009126.1
6400 QIU91361.1        CP050811.1
6401 AAC75271.1        U00096.3
6402 ABA70720.1        DQ185144.1
6403 WP_013992183.1    NG_057434.1
     AMR Gene Family
1    Erm 23S ribosomal RNA methyltransferase
2    AAC(2')
3    AAC(2')
4    AAC(2')
5    AAC(2')
6    AAC(2')
7    AAC(2')
8    AAC(2')
9    AAC(3)
10   AAC(3)
11   aminoglycoside bifunctional resistance protein
12   AAC(3)
13   AAC(3)
14   AAC(3)
15   AAC(3)
16   AAC(3)
17   AAC(3)
18   AAC(3)
19   AAC(3)
20   AAC(3)
21   AAC(3)
22   AAC(3)
23   AAC(3)
24   AAC(3)
25   AAC(3)
26   AAC(3)
27   AAC(3)
28   AAC(3)
29   AAC(3)
30   AAC(6')
⋮    ⋮
6374 VIM beta-lactamase
6375 VIM beta-lactamase
6376 VIM beta-lactamase
6377 VIM beta-lactamase
6378 VIM beta-lactamase
6379 VIM beta-lactamase
6380 VIM beta-lactamase
6381 VIM beta-lactamase
6382 VIM beta-lactamase
6383 VIM beta-lactamase
6384 VIM beta-lactamase
6385 VIM beta-lactamase
6386 VIM beta-lactamase
6387 VIM beta-lactamase
6388 VIM beta-lactamase
6389 VIM beta-lactamase
6390 VMB beta-lactamase
6391 Miscellaneous ABC-F subfamily ATP-binding cassette ribosomal protection proteins
6392 viomycin phosphotransferase
6393 ATP-binding cassette (ABC) antibiotic efflux pump
6394 WUS beta-lactamase
6395 BlaA beta-lactamase
6396 resistance-nodulation-cell division (RND) antibiotic efflux pump
6397 YEM beta-lactamase
6398 small multidrug resistance (SMR) antibiotic efflux pump
6399 small multidrug resistance (SMR) antibiotic efflux pump
6400 YOC beta-lactamase
6401 ATP-binding cassette (ABC) antibiotic efflux pump
6402 YRC beta-lactamase
6403 ZOG beta-lactamase
     Drug Class
1    lincosamide antibiotic;macrolide antibiotic;streptogramin antibiotic
2    aminoglycoside antibiotic
3    aminoglycoside antibiotic
4    aminoglycoside antibiotic
5    aminoglycoside antibiotic
6    aminoglycoside antibiotic
7    aminoglycoside antibiotic
8    aminoglycoside antibiotic
9    aminoglycoside antibiotic
10   aminoglycoside antibiotic
11   aminoglycoside antibiotic
12   aminoglycoside antibiotic
13   aminoglycoside antibiotic
14   aminoglycoside antibiotic
15   aminoglycoside antibiotic
16   aminoglycoside antibiotic
17   aminoglycoside antibiotic
18   aminoglycoside antibiotic
19   aminoglycoside antibiotic
20   aminoglycoside antibiotic
21   aminoglycoside antibiotic
22   aminoglycoside antibiotic
23   aminoglycoside antibiotic
24   aminoglycoside antibiotic
25   aminoglycoside antibiotic
26   aminoglycoside antibiotic
27   aminoglycoside antibiotic
28   aminoglycoside antibiotic
29   aminoglycoside antibiotic
30   aminoglycoside antibiotic
⋮    ⋮
6374 carbapenem;cephalosporin;penicillin beta-lactam
6375 carbapenem;cephalosporin;penicillin beta-lactam
6376 carbapenem;cephalosporin;penicillin beta-lactam
6377 carbapenem;cephalosporin;penicillin beta-lactam
6378 carbapenem;cephalosporin;penicillin beta-lactam
6379 carbapenem;cephalosporin;penicillin beta-lactam
6380 carbapenem;cephalosporin;penicillin beta-lactam
6381 carbapenem;cephalosporin;penicillin beta-lactam
6382 carbapenem;cephalosporin;penicillin beta-lactam
6383 carbapenem;cephalosporin;penicillin beta-lactam
6384 carbapenem;cephalosporin;penicillin beta-lactam
6385 carbapenem;cephalosporin;penicillin beta-lactam
6386 carbapenem;cephalosporin;penicillin beta-lactam
6387 carbapenem;cephalosporin;penicillin beta-lactam
6388 carbapenem;cephalosporin;penicillin beta-lactam
6389 carbapenem;cephalosporin;penicillin beta-lactam
6390 carbapenem;cephalosporin;penicillin beta-lactam
6391 lincosamide antibiotic;nucleoside antibiotic;pleuromutilin antibiotic;streptogramin A antibiotic;streptogramin B antibiotic;streptogramin antibiotic
6392 peptide antibiotic
6393 glycopeptide antibiotic
6394 carbapenem;penicillin beta-lactam
6395 cephalosporin;penicillin beta-lactam
6396 cephalosporin;disinfecting agents and antiseptics;fluoroquinolone antibiotic;glycopeptide antibiotic;glycylcycline;oxazolidinone antibiotic;penicillin beta-lactam;phenicol antibiotic;rifamycin antibiotic;tetracycline antibiotic
6397 carbapenem
6398 aminoglycoside antibiotic;phenicol antibiotic;tetracycline antibiotic
6399 aminoglycoside antibiotic;phenicol antibiotic;tetracycline antibiotic
6400 cephalosporin
6401 peptide antibiotic
6402 cephalosporin;penicillin beta-lactam
6403 carbapenem
     Resistance Mechanism
1    antibiotic target alteration
2    antibiotic inactivation
3    antibiotic inactivation
4    antibiotic inactivation
5    antibiotic inactivation
6    antibiotic inactivation
7    antibiotic inactivation
8    antibiotic inactivation
9    antibiotic inactivation
10   antibiotic inactivation
11   antibiotic inactivation
12   antibiotic inactivation
13   antibiotic inactivation
14   antibiotic inactivation
15   antibiotic inactivation
16   antibiotic inactivation
17   antibiotic inactivation
18   antibiotic inactivation
19   antibiotic inactivation
20   antibiotic inactivation
21   antibiotic inactivation
22   antibiotic inactivation
23   antibiotic inactivation
24   antibiotic inactivation
25   antibiotic inactivation
26   antibiotic inactivation
27   antibiotic inactivation
28   antibiotic inactivation
29   antibiotic inactivation
30   antibiotic inactivation
⋮    ⋮
6374 antibiotic inactivation
6375 antibiotic inactivation
6376 antibiotic inactivation
6377 antibiotic inactivation
6378 antibiotic inactivation
6379 antibiotic inactivation
6380 antibiotic inactivation
6381 antibiotic inactivation
6382 antibiotic inactivation
6383 antibiotic inactivation
6384 antibiotic inactivation
6385 antibiotic inactivation
6386 antibiotic inactivation
6387 antibiotic inactivation
6388 antibiotic inactivation
6389 antibiotic inactivation
6390 antibiotic inactivation
6391 antibiotic target protection
6392 antibiotic inactivation
6393 antibiotic efflux
6394 antibiotic inactivation
6395 antibiotic inactivation
6396 antibiotic efflux
6397 antibiotic inactivation
6398 antibiotic efflux
6399 antibiotic efflux
6400 antibiotic inactivation
6401 antibiotic efflux
6402 antibiotic inactivation
6403 antibiotic inactivation